# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9O6N3olRmfx0E-xAnZlQIumkzDpZM1F
"""

N=3
for x in range(0,N):
  print("*"*N,end="")
  print()

N=5
for x in range(1,N+1):
  print("*"*x,end="")
  print()

N=5
for x in range(1,N+1):
  for y in range(1,x+1):
    print(y,end="")

  print()

N=5
for x in range(1,N+1):
  for y in range(1,x+1):
    print(x,end="")

  print()

n=10
for x in range(0,n):
  for y in range(0,n-x):
    print("*",end="")
  print()

n=10
for x in range(0,n+1):
  for y in range(1,n-x+1):
    print(y,end="")
  print()

n=5
for x in range(0,n+1):
  for s in range(n-x):
    print(" ",end="")
  for y in range(0,x+x-1):
    print("*",end="")
  print()

n=3
for x in range(0,n):
  for y in range(x):
    print(" ",end="")
  for z in range(2*(n-x)-1):
    print("*",end=" ")
  print()

n=5
nst=1
nss=n-1
for x in range(0,n*2):
  for space in range(nss):
    print(" ",end="")

  for star in range(nst):
    print("*",end="")
  if x==n-1:
    nss=nss
    nst=nst
  elif(x>=n):
     nss=nss+1
     nst=nst-2
  else:

    nss=nss-1
    nst=nst+2
  print()

n=input("Enter the value of N:")
nss=n-1
nst=1
direction=1
for x in range(n*2):
  print("*"*nst+" "*nss)
  if x==n-1:
    direction=-1
  else:

    nst+=2*direction
    nss+=1*direction

n = 5
nst = 1
nss = n - 1
direction = 1        # 1 = growing stars, -1 = shrinking

for x in range(n*2):
    print(" " * nss + "*" * nst)

    if x == n - 1:              # just printed the peak
        direction = -1           # flip direction, don't move yet
    else:
        nss -= 1 * direction
        nst += 2 * direction

n=5
nst=1
direction=1
nss=n-1

for x in range(n*2):
  print("*"*nst)
  if x==n-1:
    direction=-1
  nst+=1*direction

n=5
start=1
for x in range(1,n+1):
  if(x%2!=0):
    start=1
  else:
    start=0
  for y in range(x):
    print(start,end="")
    start=1-start


  print()

n=3
val=1
for x in range(1,n+1):
  for y in range(1,n*2+1):
    if (x+1)<=y<=((n*2)-x):
      print("#",end="")
    else:

      if y>n:

        val-=1
        print(val,end="")

      else:
        print(val,end="")
        val+=1

  print()
  val=1

n=3
for x in range(1,n+1):
  val=1
  for y in range(1,(n*2)+1):
    if (x+1)<=y<=((n*2)-x):
      print(" ",end="")
    else:
      if(y<=n):
        print(val,end="")
        val+=1
      else:
        val-=1
        print(val,end="")

  print()

val=1
n=5
for x in range(1,n+1):
  for y in range(x):
    print(val," ",end="")
    val+=1
  print()

n=3
for x in range(1,n+1):
  val=65
  for y in range(x,0,-1):
    print(chr(val),end="")
    val+=1
  print()

n=5
i=n
val=65
for x in range(1,n+1):

  for y in range(x):
    print(chr(val),end="")

  print()
  val+=1

n=4
star=1

for x in range(1,n+1):
  val=97
  for space in range(n-x):
    print(" ",end="")
  for alpha in range(1,star+1):
    print( chr(val),end="")
    if alpha>=x:
      val-=1
    else:
      val+=1
  star+=2
  print()

n=6
val=97+n-1
for x in range(1,n+1):
  vall=val
  for y in range(x):
    print(chr(vall),end="")
    vall+=1


  val-=1
  print()